// Print the Fibonacci series up to n terms using a while loop
public class q19 {
    public static void main(String[] args) {
        int n = 10; // number of terms to print
        int firstTerm = 0, secondTerm = 1;

        System.out.println("Fibonacci Series up to " + n + " terms:");

        int count = 0;
        while (count < n) {
            System.out.print(firstTerm + " "); //print cuurrent term

            // compute the next term
            int nextTerm = firstTerm + secondTerm; //calculate next term
            firstTerm = secondTerm; //update first term to second term
            secondTerm = nextTerm;  //update second term to next term

            count++; //increment count to keep track of how many terms have been printed
        }
    }
}
//fibonacci series: The Fibonacci sequence is a series of numbers where each number is the sum of the two preceding ones, usually starting with 0 and 1. The sequence goes: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, and so on. Each term after the first two is generated by adding the two previous terms together.
//example: The first 10 terms of the Fibonacci series are: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34